### ISSUE TITLE
Convert mockups into scss and ejs.

### ISSUE THREAD

**Issue by brock8503** [project-monolith/monolith-frontend#1]
Need to create the pixel blueprint/schematic.

**Comment by jhammerquist** [comment]
Kyle, I am trying to picture what you're talking about. Do you have any
examples of a pixel schematic from other projects you could share?

**Comment by brock8503** [comment]
@jhammerquist something similar to http://matthewjamestaylor.com/blog/ultimate-3-column-holy-grail-pixels-dimensions.gif

Just a simple blueprint so a developer can place all the elements appropriately.

**Comment by brock8503** [comment]
@jhammerquist Any updates on this front?

**Comment by brock8503** [comment]
@jhammerquist I'm slowing making progress here: http://take.ms/oqQFg
