### ISSUE TITLE
front end install problem

### ISSUE THREAD

**Issue by eldang** [project-monolith/monolith-frontend#11]
When I try to follow the instructions in the readme, at the `npm install` stage (after installing all the listed prerequisites) I ran into:

```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/eldan/Documents/github/monolith-frontend/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eldan/Documents/github/monolith-frontend/npm-debug.log
```

I tried manually installing `node-sass`, then repeated the npm install, and got the same error.  I'll see if I can upload `npm-debug.log` to slack - it's way too long for pasting it here to be a good idea.

**Comment by mdunsmuir** [comment]
I fixed this (or something like it) by manually installing the homebrew
package node010 instead of just "node".

**Comment by eldang** [comment]
I installed `n` and used that to switch to 0.10.0, but got the same error message about `node-sass`.  I'm trying not to have to put other projects on an old version of node in order to run this one, but I can try that tomorrow and at least see if it works.

**Comment by brock8503** [comment]
@eldang can you try again with node 12.0, I had to bump the version for node-sass in the `package.json` file.

**Comment by eldang** [comment]
@brock8503 Fix verified!  Thank you.
I currently just see a blank page at localhost:9000. Is this a sign of another problem, or just the current state of this repo?

**Comment by brock8503** [comment]
Do you have the backend up and running? I probably should link the instructions for running the backend in this readme.

**Comment by mdunsmuir** [comment]
I have always had the same problem with the frontend; even with the backend
running, the page stays blank.

**Comment by eldang** [comment]
@brock8503 thanks for updating the instructions. I hadn't realised I needed to run the separate backend from the old repo; with that and the node v12.2 version bump it's working.

@mdunsmuir dunno if this is the problem you're having, but I've found that it works properly if I run `grunt serve` but I get the blank page with `grunt server`.
