### ISSUE TITLE
Embed font into the css.

### ISSUE THREAD

**Issue by brock8503** [project-monolith/monolith-frontend#12]
Use the metro standard fonts for the project.

@jhammerquist can you point me to the font `tff` file.

**Comment by jhammerquist** [comment]
Metro uses Humanist777. We do not have that font but we do have Frutiger, a close cousin by the same designer. The Frutiger family is located here:
https://drive.google.com/open?id=0BxJ7o-CNc3UEZFJ4OE1oLWRrLWc&authuser=0
