### ISSUE TITLE
Create svg's of all the icons.

### ISSUE THREAD

**Issue by brock8503** [project-monolith/monolith-frontend#16]
Picture of icons. http://monosnap.com/image/fVqpMYfIzhDQXpHg14SdQTwyjGs3d4

**Comment by alicefeng** [comment]
SVG's of the icons have been created.  An Illustrator file has been added to our Google Drive under Design Assets>04_Illustrator and 4 svg files have been added to Design Assets>02_Icons.

I created SVGs for these 4 icons:
1. You are here (header)
2. You are here (map)
3. Bike share
4. Car share

**Comment by jhammerquist** [comment]
Nice work Alice! Those look great.

**Comment by eldang** [comment]
Thank you Alice!  I'm starting to use those on the map now.
